spring.application.name=backend
server.port=${PORT:8080}

# PostgreSQL Database Connection
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:2007}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT Secret
jwt.secret=${JWT_SECRET:55d285b546b3fefe2139dcad7096739ea100b40ec4be5ed603ec5e9541577789}
jwt.expiration=86400000
